### ISSUE TITLE
Backwards Compatibility with New Parser Featurization, Unit Testing

### ISSUE THREAD

**Issue by NC-Zhao** [kamilkrukowski/FinDocNLP#103]
I only changed `_parse_unannotated_text` and `_parse_annotated_text` (some functions are commented out but remains unchanged). The code is ready to run but unit test is not done. There is a small demo under the `examples` folder that checks the text field found. But I don't know how to run `parser._parse_annotated_text()` on a specific file. Someone please help me and add that to the jupyter notebook, thank you! Then I will make other tests to make sure that the new parser finds what need to be find. 

And here are some issues I found:
- table in span
  - currently only detect the 'span in table' situation. However, there could be the case with span->table->annotation. 
  - if fix, the `in_table` as a list is not enough, and the feature generation function needs to be adjust accordingly. 
- page number unsupported yet. It is a quick fix by adding it as a python attribute to the element object, but that raises a conflict with the feature generation step.

**Comment by kamilkrukowski** [comment]
I've added the start to a unit test --> it calls the functions you need

**Comment by kamilkrukowski** [comment]
Our current transformer model does not use features besides 'span_text'. It is unclear when this will change, or if it will in the near term. Thus, advancing the parsing without support for previous features is fine for this stage of development.

If we revisit this, we could consider a 'span_text idx' tag instead of 'page number' that tracks the order of 'span_text' text elements in a doc.

**Comment by NC-Zhao** [comment]
Also changes the `get_driver_path` from generating url into generating file path
